"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { Activity, Actor, Contact, Customer } from "@/lib/crm/types";

type View="dashboard"|"customers"|"contacts"|"activities";
type Summary={customerCount:number;leadCount:number;contactCount:number;recentActivityCount:number;upcomingFollowUps:{id:string;name:string;nextFollowUpAt:string}[]};
type FormState={kind:"customer"|"contact"|"activity";item?:Customer|Contact|Activity}|null;

async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(path,{...init,headers:{"content-type":"application/json",...(init?.headers||{})}});const json=await response.json();if(!response.ok||!json.ok)throw new Error(json.error?.message||`请求失败（${response.status}）`);return json.data;}
const date=(value:string|null|undefined)=>value?new Intl.DateTimeFormat("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value)):"—";
const inputDate=(value:string|null|undefined)=>{if(!value)return "";const d=new Date(value);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16);};

export function CrmApp(){
  const [view,setView]=useState<View>("dashboard");const [actor,setActor]=useState<Actor|null>(null);const [users,setUsers]=useState<Actor[]>([]);
  const [summary,setSummary]=useState<Summary|null>(null);const [customers,setCustomers]=useState<Customer[]>([]);const [contacts,setContacts]=useState<Contact[]>([]);const [activities,setActivities]=useState<Activity[]>([]);
  const [query,setQuery]=useState("");const [stage,setStage]=useState("");const [activityType,setActivityType]=useState("");const [busy,setBusy]=useState(true);const [message,setMessage]=useState("");const [form,setForm]=useState<FormState>(null);const [detail,setDetail]=useState<Customer|Contact|Activity|null>(null);

  const load=useCallback(async()=>{setBusy(true);try{const boot=await api<{actor:Actor;users:Actor[];summary:Summary}>("/api/crm/bootstrap");const [c,p,a]=await Promise.all([api<{items:Customer[]}>("/api/crm/customers?pageSize=100"),api<{items:Contact[]}>("/api/crm/contacts?pageSize=100"),api<{items:Activity[]}>("/api/crm/activities?pageSize=100")]);setActor(boot.actor);setUsers(boot.users);setSummary(boot.summary);setCustomers(c.items);setContacts(p.items);setActivities(a.items);}catch(error){setMessage(error instanceof Error?error.message:"加载失败");}finally{setBusy(false);}},[]);
  useEffect(()=>{void load();},[load]);

  const filteredCustomers=useMemo(()=>customers.filter((item)=>(!stage||item.stage===stage)&&[item.name,item.industry,item.phone,item.email].some((value)=>String(value||"").toLowerCase().includes(query.toLowerCase()))),[customers,query,stage]);
  const filteredContacts=useMemo(()=>contacts.filter((item)=>[item.name,item.title,item.phone,item.email,item.customerName].some((value)=>String(value||"").toLowerCase().includes(query.toLowerCase()))),[contacts,query]);
  const filteredActivities=useMemo(()=>activities.filter((item)=>(!activityType||item.type===activityType)&&[item.subject,item.content,item.customerName].some((value)=>String(value||"").toLowerCase().includes(query.toLowerCase()))),[activities,query,activityType]);

  async function switchActor(userId:string){setBusy(true);try{await api("/api/session",{method:"POST",body:JSON.stringify({userId})});setQuery("");await load();setMessage("演示账号已切换");}catch(error){setMessage(error instanceof Error?error.message:"切换失败");}finally{setBusy(false);}}
  async function save(payload:Record<string,unknown>){if(!form)return;const resource=form.kind==="customer"?"customers":form.kind==="contact"?"contacts":"activities";const current=form.item;await api(`/api/crm/${resource}`,{method:current?"PATCH":"POST",body:JSON.stringify(current?{id:current.id,patch:payload}:payload)});setForm(null);setMessage("保存成功");await load();}
  async function archive(item:Customer|Contact|Activity,kind:NonNullable<FormState>["kind"]){if(!confirm("确定归档这条记录吗？"))return;const resource=kind==="customer"?"customers":kind==="contact"?"contacts":"activities";await api(`/api/crm/${resource}`,{method:"PATCH",body:JSON.stringify({id:item.id,patch:{archived:true}})});setMessage("已归档");await load();}
  async function archiveDemo(){if(!confirm("归档所有预置示例数据？可通过 bun run db:reset 恢复。"))return;await api("/api/crm/archive-demo",{method:"POST",body:"{}"});setMessage("示例数据已归档");await load();}

  const titles:Record<View,[string,string]>={dashboard:["工作台","掌握客户关系与跟进节奏"],customers:["客户管理","维护客户信息与生命周期"],contacts:["联系人","记录客户组织中的关键人员"],activities:["跟进记录","沉淀每一次客户互动"]};
  return <div className="shell">
    <aside className="sidebar"><a className="brand" href="/"><span className="brandMark">✦</span><span>明日 CRM</span></a><nav>{(["dashboard","customers","contacts","activities"] as View[]).map((item)=><button key={item} className={view===item?"active":""} onClick={()=>{setView(item);setQuery("");}}><span>{item==="dashboard"?"▦":item==="customers"?"◉":item==="contacts"?"♙":"◷"}</span>{item==="dashboard"?"总览":item==="customers"?"客户":item==="contacts"?"联系人":"跟进记录"}</button>)}</nav><a className="demoLink" href="/demo">⚙ MCP 演示控制台</a><div className="profile"><strong>{actor?.name||"正在加载…"}</strong><span>{actor?.isAdmin?"管理员 · 可查看全部数据":"销售 · 仅查看本人数据"}</span></div></aside>
    <main className="main"><header className="topbar"><div><h1>{titles[view][0]}</h1><p>{titles[view][1]}</p></div><div className="topActions"><select aria-label="切换演示账号" value={actor?.id||""} onChange={(event)=>void switchActor(event.target.value)}>{users.map((user)=><option value={user.id} key={user.id}>{user.name}</option>)}</select><button className="button" onClick={()=>void load()}>↻ 刷新</button></div></header>
      <div className="content">
        {view==="dashboard"&&<Dashboard summary={summary} customers={customers} onOpen={setDetail} actor={actor} onArchiveDemo={()=>void archiveDemo()}/>} 
        {view==="customers"&&<><Toolbar query={query} setQuery={setQuery} placeholder="搜索客户、行业、电话或邮箱"><select value={stage} onChange={(e)=>setStage(e.target.value)}><option value="">全部阶段</option>{["线索","意向","客户","停用"].map(x=><option key={x}>{x}</option>)}</select><button className="button primary" onClick={()=>setForm({kind:"customer"})}>＋ 新建客户</button></Toolbar><CustomerTable items={filteredCustomers} onOpen={setDetail} onEdit={(item)=>setForm({kind:"customer",item})} onArchive={(item)=>void archive(item,"customer")}/></>}
        {view==="contacts"&&<><Toolbar query={query} setQuery={setQuery} placeholder="搜索姓名、职位、客户或联系方式"><button className="button primary" onClick={()=>setForm({kind:"contact"})}>＋ 新建联系人</button></Toolbar><ContactTable items={filteredContacts} onOpen={setDetail} onEdit={(item)=>setForm({kind:"contact",item})} onArchive={(item)=>void archive(item,"contact")}/></>}
        {view==="activities"&&<><Toolbar query={query} setQuery={setQuery} placeholder="搜索主题、客户或跟进内容"><select value={activityType} onChange={(e)=>setActivityType(e.target.value)}><option value="">全部类型</option>{["电话","会议","邮件","拜访","其他"].map(x=><option key={x}>{x}</option>)}</select><button className="button primary" onClick={()=>setForm({kind:"activity"})}>＋ 新增跟进</button></Toolbar><ActivityTable items={filteredActivities} onOpen={setDetail} onEdit={(item)=>setForm({kind:"activity",item})} onArchive={(item)=>void archive(item,"activity")}/></>}
      </div>
    </main>
    <nav className="mobileNav">{(["dashboard","customers","contacts","activities"] as View[]).map((item)=><button key={item} className={view===item?"active":""} onClick={()=>setView(item)}>{item==="dashboard"?"▦ 总览":item==="customers"?"◉ 客户":item==="contacts"?"♙ 联系人":"◷ 跟进"}</button>)}</nav>
    {form&&<EntityModal state={form} customers={customers} contacts={contacts} onClose={()=>setForm(null)} onSave={save}/>} {detail&&<DetailDrawer item={detail} onClose={()=>setDetail(null)}/>} {busy&&<div className="loading"><span/></div>} {message&&<button className="toast" onClick={()=>setMessage("")}>{message}</button>}
  </div>;
}

function Toolbar({query,setQuery,placeholder,children}:{query:string;setQuery:(value:string)=>void;placeholder:string;children:React.ReactNode}){return <div className="toolbar"><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder={placeholder}/><div>{children}</div></div>;}
function Dashboard({summary,customers,onOpen,actor,onArchiveDemo}:{summary:Summary|null;customers:Customer[];onOpen:(item:Customer)=>void;actor:Actor|null;onArchiveDemo:()=>void}){const cards=[["◉","客户总数",summary?.customerCount??"—"],["⌁","线索与意向",summary?.leadCount??"—"],["♙","联系人",summary?.contactCount??"—"],["◷","近 30 天跟进",summary?.recentActivityCount??"—"]];return <><div className="stats">{cards.map(([icon,label,value])=><article className="stat" key={label}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></article>)}</div><div className="dashboardGrid"><section className="panel"><div className="panelHead"><strong>最近客户</strong></div><CustomerTable compact items={customers.slice(0,5)} onOpen={onOpen}/></section><section className="panel"><div className="panelHead"><strong>待跟进</strong>{actor?.isAdmin&&<button className="textDanger" onClick={onArchiveDemo}>归档示例数据</button>}</div><div className="upcoming">{summary?.upcomingFollowUps.length?summary.upcomingFollowUps.map((item)=><button key={item.id} onClick={()=>{const customer=customers.find(x=>x.id===item.id);if(customer)onOpen(customer);}}><span>{item.name}</span><time>{date(item.nextFollowUpAt)}</time></button>):<div className="empty">暂无待跟进客户</div>}</div></section></div></>;}
function CustomerTable({items,onOpen,onEdit,onArchive,compact=false}:{items:Customer[];onOpen:(item:Customer)=>void;onEdit?:(item:Customer)=>void;onArchive?:(item:Customer)=>void;compact?:boolean}){return <div className="tableWrap"><table><thead><tr><th>客户</th><th>阶段</th><th>行业</th><th>负责人</th><th>下次跟进</th>{!compact&&<th>操作</th>}</tr></thead><tbody>{items.map(item=><tr key={item.id}><td><button className="link" onClick={()=>onOpen(item)}>{item.name}</button></td><td><span className={`pill stage-${item.stage}`}>{item.stage}</span></td><td>{item.industry||"—"}</td><td>{item.ownerName}</td><td>{date(item.nextFollowUpAt)}</td>{!compact&&<td><button className="rowAction" onClick={()=>onEdit?.(item)}>编辑</button><button className="rowAction danger" onClick={()=>onArchive?.(item)}>归档</button></td>}</tr>)}{!items.length&&<tr><td colSpan={6} className="empty">暂无数据</td></tr>}</tbody></table></div>;}
function ContactTable({items,onOpen,onEdit,onArchive}:{items:Contact[];onOpen:(item:Contact)=>void;onEdit:(item:Contact)=>void;onArchive:(item:Contact)=>void}){return <div className="panel tableWrap"><table><thead><tr><th>联系人</th><th>职位</th><th>客户</th><th>手机</th><th>邮箱</th><th>操作</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><button className="link" onClick={()=>onOpen(item)}>{item.name}</button>{item.primary&&<span className="primaryTag">主要</span>}</td><td>{item.title||"—"}</td><td>{item.customerName}</td><td>{item.phone||"—"}</td><td>{item.email||"—"}</td><td><button className="rowAction" onClick={()=>onEdit(item)}>编辑</button><button className="rowAction danger" onClick={()=>onArchive(item)}>归档</button></td></tr>)}{!items.length&&<tr><td colSpan={6} className="empty">暂无数据</td></tr>}</tbody></table></div>;}
function ActivityTable({items,onOpen,onEdit,onArchive}:{items:Activity[];onOpen:(item:Activity)=>void;onEdit:(item:Activity)=>void;onArchive:(item:Activity)=>void}){return <div className="panel tableWrap"><table><thead><tr><th>主题</th><th>类型</th><th>客户</th><th>发生时间</th><th>下次跟进</th><th>操作</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><button className="link" onClick={()=>onOpen(item)}>{item.subject}</button></td><td><span className="pill">{item.type}</span></td><td>{item.customerName}</td><td>{date(item.occurredAt)}</td><td>{date(item.nextFollowUpAt)}</td><td><button className="rowAction" onClick={()=>onEdit(item)}>编辑</button><button className="rowAction danger" onClick={()=>onArchive(item)}>归档</button></td></tr>)}{!items.length&&<tr><td colSpan={6} className="empty">暂无数据</td></tr>}</tbody></table></div>;}

function EntityModal({state,customers,contacts,onClose,onSave}:{state:NonNullable<FormState>;customers:Customer[];contacts:Contact[];onClose:()=>void;onSave:(payload:Record<string,unknown>)=>Promise<void>}){const [saving,setSaving]=useState(false);const item=state.item;async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);const raw=Object.fromEntries(new FormData(event.currentTarget));const values:Record<string,unknown>={...raw};for(const key of Object.keys(values))if(values[key]==="")values[key]=null;try{await onSave(values);}finally{setSaving(false);}}return <div className="overlay"><form className="modal" onSubmit={submit}><div className="modalHead"><h2>{item?"编辑":"新建"}{state.kind==="customer"?"客户":state.kind==="contact"?"联系人":"跟进记录"}</h2><button type="button" onClick={onClose}>×</button></div><div className="formGrid">{state.kind==="customer"&&<><Field name="name" label="客户名称" required defaultValue={(item as Customer)?.name}/><Select name="stage" label="客户阶段" values={["线索","意向","客户","停用"]} defaultValue={(item as Customer)?.stage||"线索"}/><Field name="industry" label="行业" defaultValue={(item as Customer)?.industry}/><Field name="source" label="来源" defaultValue={(item as Customer)?.source}/><Field name="phone" label="联系电话" defaultValue={(item as Customer)?.phone}/><Field name="email" label="邮箱" type="email" defaultValue={(item as Customer)?.email}/><Field name="website" label="官网" defaultValue={(item as Customer)?.website}/><Field name="nextFollowUpAt" label="下次跟进" type="datetime-local" defaultValue={inputDate((item as Customer)?.nextFollowUpAt)}/><Field className="full" name="notes" label="备注" textarea defaultValue={(item as Customer)?.notes}/></>}
      {state.kind==="contact"&&<><Field name="name" label="联系人姓名" required defaultValue={(item as Contact)?.name}/><label>关联客户<select name="customerId" required defaultValue={(item as Contact)?.customerId||""}><option value="">请选择</option>{customers.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><Field name="title" label="职位" defaultValue={(item as Contact)?.title}/><Field name="phone" label="手机" defaultValue={(item as Contact)?.phone}/><Field name="email" label="邮箱" type="email" defaultValue={(item as Contact)?.email}/><Field name="wechat" label="微信" defaultValue={(item as Contact)?.wechat}/><Field className="full" name="notes" label="备注" textarea defaultValue={(item as Contact)?.notes}/></>}
      {state.kind==="activity"&&<><Field name="subject" label="跟进主题" required defaultValue={(item as Activity)?.subject}/><Select name="type" label="跟进类型" values={["电话","会议","邮件","拜访","其他"]} defaultValue={(item as Activity)?.type||"电话"}/><label>关联客户<select name="customerId" required defaultValue={(item as Activity)?.customerId||""}><option value="">请选择</option>{customers.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>关联联系人<select name="contactId" defaultValue={(item as Activity)?.contactId||""}><option value="">不关联</option>{contacts.map(x=><option value={x.id} key={x.id}>{x.name} · {x.customerName}</option>)}</select></label><Field name="occurredAt" label="发生时间" type="datetime-local" required defaultValue={inputDate((item as Activity)?.occurredAt||new Date().toISOString())}/><Field name="nextFollowUpAt" label="下次跟进" type="datetime-local" defaultValue={inputDate((item as Activity)?.nextFollowUpAt)}/><Field className="full" name="content" label="跟进内容" textarea defaultValue={(item as Activity)?.content}/></>}</div><div className="modalFoot"><button type="button" className="button" onClick={onClose}>取消</button><button className="button primary" disabled={saving}>{saving?"保存中…":"保存"}</button></div></form></div>;}
function Field({label,textarea,className="",defaultValue,...props}:{label:string;textarea?:boolean;className?:string;defaultValue?:string|null}&Omit<React.InputHTMLAttributes<HTMLInputElement>,"defaultValue">){return <label className={className}>{label}{textarea?<textarea name={props.name} defaultValue={defaultValue||""}/>:<input {...props} defaultValue={defaultValue||""}/>}</label>;}
function Select({label,values,...props}:{label:string;values:string[]}&React.SelectHTMLAttributes<HTMLSelectElement>){return <label>{label}<select {...props}>{values.map(value=><option key={value}>{value}</option>)}</select></label>;}
function DetailDrawer({item,onClose}:{item:Customer|Contact|Activity;onClose:()=>void}){const title="subject" in item?item.subject:item.name;const labels:Record<string,string>={stage:"客户阶段",industry:"行业",source:"来源",phone:"电话",email:"邮箱",website:"官网",address:"地址",notes:"备注",ownerName:"负责人",lastFollowUpAt:"最近跟进",nextFollowUpAt:"下次跟进",customerName:"关联客户",title:"职位",wechat:"微信",primary:"主要联系人",type:"跟进类型",content:"跟进内容",occurredAt:"发生时间",contactName:"关联联系人"};return <div className="overlay" onMouseDown={onClose}><aside className="drawer" onMouseDown={(e)=>e.stopPropagation()}><div className="drawerHead"><div><small>CRM 详情</small><h2>{title}</h2></div><button onClick={onClose}>×</button></div><div className="detailGrid">{Object.entries(item).filter(([key,value])=>labels[key]&&value!==null&&value!=="").map(([key,value])=><div className={key==="notes"||key==="content"?"wide":""} key={key}><small>{labels[key]}</small><p>{key.endsWith("At")?date(String(value)):typeof value==="boolean"?(value?"是":"否"):String(value)}</p></div>)}</div></aside></div>;}
