"use client";

import { useEffect, useState } from "react";

export function DemoConsole({baseUrl}:{baseUrl:string}){
  const [health,setHealth]=useState<"loading"|"ok"|"error">("loading");const [copied,setCopied]=useState("");
  const endpoints=[{label:"MCP Streamable HTTP",value:`${baseUrl}/api/mcp`},{label:"OAuth Authorization Server",value:`${baseUrl}/.well-known/oauth-authorization-server`},{label:"Protected Resource Metadata",value:`${baseUrl}/.well-known/oauth-protected-resource/api/mcp`}];
  useEffect(()=>{fetch("/api/health").then((r)=>{if(!r.ok)throw new Error();setHealth("ok");}).catch(()=>setHealth("error"));},[]);
  async function copy(value:string,label:string){await navigator.clipboard.writeText(value);setCopied(label);setTimeout(()=>setCopied(""),1600);}
  return <main className="demoPage"><header className="demoHero"><a href="/">← 返回 CRM</a><span className={`health ${health}`}>{health==="loading"?"检测中":health==="ok"?"服务正常":"服务异常"}</span><h1>MCP 演示控制台</h1><p>确认本地 CRM、OAuth 2.1 和 MCP 服务状态，并复制豆包工作连接器地址。</p></header><section className="demoSection"><div className="stepTitle"><span>1</span><div><h2>确认公开访问地址</h2><p>豆包工作无法直接访问你电脑上的 localhost，需要通过 HTTPS 隧道访问本地 Next.js 服务。</p></div></div><pre><code>cloudflared tunnel --url http://localhost:3000</code></pre><p className="note">复制命令返回的 HTTPS 域名，写入 <code>APP_BASE_URL</code> 后重启服务。当前识别地址：<strong>{baseUrl}</strong></p></section><section className="demoSection"><div className="stepTitle"><span>2</span><div><h2>复制连接器地址</h2><p>在豆包工作创建自定义 MCP 连接器时使用第一项地址。</p></div></div><div className="endpointList">{endpoints.map((item)=><div className="endpoint" key={item.label}><div><small>{item.label}</small><code>{item.value}</code></div><button onClick={()=>void copy(item.value,item.label)}>{copied===item.label?"已复制":"复制"}</button></div>)}</div></section><section className="demoSection"><div className="stepTitle"><span>3</span><div><h2>完成 OAuth 授权</h2><p>豆包会自动发现 OAuth 元数据、动态注册回调地址，并打开本项目的授权页。</p></div></div><ol className="flow"><li>选择一个内置 CRM 演示账号</li><li>确认允许查询和维护 CRM 数据</li><li>本地服务向豆包回调授权码</li><li>豆包使用 PKCE 换取 Token 并连接 MCP</li></ol><div className="warning">授权完成后的最终页面由豆包客户端提供；本项目不会截获或伪造豆包的回调页面。</div></section><section className="demoSection"><div className="stepTitle"><span>4</span><div><h2>推荐演示问题</h2><p>连接成功后，在豆包工作中依次测试权限、查询和写入。</p></div></div><div className="prompts"><button onClick={()=>void copy("汇总当前账号能看到的客户和最近 30 天跟进情况。","prompt1")}>汇总我的 CRM 数据</button><button onClick={()=>void copy("搜索所有处于意向阶段的客户，并告诉我下一步应该优先跟进谁。","prompt2")}>分析意向客户</button><button onClick={()=>void copy("为远景科技新增一条电话跟进：已确认下周进行方案评审。","prompt3")}>新增跟进记录</button></div></section></main>;
}
